import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Header } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-white dark:bg-[#352F44]`}>
        <ThemeProvider
          attribute='class'
          enableSystem={false}
          storageKey='next-movie-theme'
        >
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
